Repository rt-net/crane_x7_ros, pull requests merged in 2022-11, with the labels that each got.

#163 Update README.md
  README.md
Labels: Type: Documentation

#164 RealSense D435搭載モデルに対応
  crane_x7_examples/README.md
  crane_x7_examples/launch/demo.launch.py
  crane_x7_examples/package.xml
Labels: Type: Feature, ROS 2

#162 Support ROS 2 Humble
  .ci.rosinstall
  .github/workflows/industrial_ci.yml
  README.en.md
  README.md
  crane_x7_control/config/crane_x7_controllers.yaml
  crane_x7_control/include/crane_x7_control/crane_x7_hardware.hpp
  crane_x7_control/launch/crane_x7_control.launch.py
  crane_x7_control/src/crane_x7_hardware.cpp
  crane_x7_examples/README.md
  crane_x7_examples/src/joint_values.cpp
  crane_x7_gazebo/gui/gui.config
  crane_x7_gazebo/launch/crane_x7_with_table.launch.py
  crane_x7_gazebo/package.xml
  crane_x7_moveit_config/config/joint_limits.yaml
  crane_x7_moveit_config/launch/run_move_group.launch.py
Labels: Type: Feature

#165 Add use_sim_time arg to example.launch.py
  crane_x7_examples/README.md
  crane_x7_examples/launch/example.launch.py
Labels: Type: Bug

#167 Foxy版パッケージのバージョン表記更新
  crane_x7/package.xml
  crane_x7_control/package.xml
  crane_x7_examples/package.xml
  crane_x7_gazebo/package.xml
  crane_x7_moveit_config/package.xml
Labels: Type: Documentation

#166 Humble版パッケージのバージョン表記更新
  crane_x7/package.xml
  crane_x7_control/package.xml
  crane_x7_examples/package.xml
  crane_x7_gazebo/package.xml
  crane_x7_moveit_config/package.xml
Labels: Type: Documentation
